# Generated by Django 4.2 on 2024-01-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_pay_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="pay_day",
            field=models.DateTimeField(),
        ),
    ]
