# Generated by Django 4.2 on 2024-01-23 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_order_pay_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="pay_day",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 28, 21, 57, 40, 260964, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
