# Generated by Django 4.2 on 2024-01-24 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_alter_order_pay_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="pay_day",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 29, 0, 0, 20, 464233, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
